name: Build and Publish Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-publish:
    uses: halkeye/halkeye/.github/workflows/build-upstream-docker.yaml@master
    secrets: inherit
    permissions:
      contents: write
      packages: write
    with:
      upstream_version: "da15a6ec744281c6ae2b970c72d45b93f8a75109"
      upstream_repo: "https://github.com/lowercasename/gathio"
      checkout_upstream_repo: "lowercasename/gathio"
      run_number: "${{ github.run_number }}"
      username: "${{ github.repository_owner }}"
      repository: "${{ github.repository }}"
